// ================================================
//  ShopKart Product Database
//  Complete product data for all categories
// ================================================

const productsData = [
    // ===== ELECTRONICS =====
    {
        id: 1,
        name: "iPhone 15 Pro Max",
        category: "electronics",
        price: 134900,
        originalPrice: 159900,
        image: "https://images.unsplash.com/photo-1696446702062-6a4ea5b90e1c?w=400",
        description: "Latest iPhone with A17 Pro chip, titanium design, and advanced camera system",
        brand: "Apple",
        model: "iPhone 15 Pro Max",
        rating: 4.8,
        reviews: 1250,
        inStock: true,
        material: "Titanium",
        warranty: "1 Year Apple Warranty"
    },
    {
        id: 2,
        name: "Samsung Galaxy S24 Ultra",
        category: "electronics",
        price: 124999,
        originalPrice: 139999,
        image: "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=400",
        description: "Premium Samsung flagship with S Pen, 200MP camera, and AI features",
        brand: "Samsung",
        model: "Galaxy S24 Ultra",
        rating: 4.7,
        reviews: 980,
        inStock: true,
        material: "Aluminum & Glass",
        warranty: "1 Year Warranty"
    },
    {
        id: 3,
        name: "MacBook Pro M3",
        category: "electronics",
        price: 169900,
        originalPrice: 199900,
        image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400",
        description: "Powerful MacBook Pro with M3 chip, stunning Liquid Retina XDR display",
        brand: "Apple",
        model: "MacBook Pro 14-inch M3",
        rating: 4.9,
        reviews: 750,
        inStock: true,
        material: "Aluminum",
        warranty: "1 Year AppleCare"
    },
    {
        id: 4,
        name: "Dell XPS 15",
        category: "electronics",
        price: 145000,
        originalPrice: 165000,
        image: "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=400",
        description: "Premium Windows laptop with Intel i9, NVIDIA RTX graphics",
        brand: "Dell",
        model: "XPS 15 9530",
        rating: 4.6,
        reviews: 540,
        inStock: true,
        material: "Carbon Fiber",
        warranty: "1 Year Onsite Warranty"
    },
    {
        id: 5,
        name: "Sony WH-1000XM5",
        category: "electronics",
        price: 29990,
        originalPrice: 34990,
        image: "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=400",
        description: "Industry-leading noise cancelling wireless headphones",
        brand: "Sony",
        model: "WH-1000XM5",
        rating: 4.8,
        reviews: 2150,
        inStock: true,
        material: "Plastic & Leather",
        warranty: "1 Year Warranty"
    },
    {
        id: 6,
        name: "iPad Air M2",
        category: "electronics",
        price: 59900,
        originalPrice: 69900,
        image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400",
        description: "Powerful tablet with M2 chip, perfect for creativity and productivity",
        brand: "Apple",
        model: "iPad Air 11-inch",
        rating: 4.7,
        reviews: 890,
        inStock: true,
        material: "Aluminum",
        warranty: "1 Year Warranty"
    },
    {
        id: 7,
        name: "Canon EOS R6 Mark II",
        category: "electronics",
        price: 234990,
        originalPrice: 259990,
        image: "https://images.unsplash.com/photo-1606980875446-5a7c7f6d3f5e?w=400",
        description: "Professional mirrorless camera with 24.2MP sensor and 4K video",
        brand: "Canon",
        model: "EOS R6 Mark II",
        rating: 4.9,
        reviews: 340,
        inStock: true,
        material: "Magnesium Alloy",
        warranty: "2 Year Warranty"
    },
    {
        id: 8,
        name: "Apple Watch Series 9",
        category: "electronics",
        price: 41900,
        originalPrice: 49900,
        image: "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=400",
        description: "Advanced smartwatch with health monitoring and fitness tracking",
        brand: "Apple",
        model: "Watch Series 9",
        rating: 4.6,
        reviews: 1580,
        inStock: true,
        material: "Aluminum",
        warranty: "1 Year Warranty"
    },

    // ===== FASHION - MEN =====
    {
        id: 9,
        name: "Men's Casual Shirt",
        category: "fashion",
        price: 1499,
        originalPrice: 2499,
        image: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=400",
        description: "Premium cotton casual shirt, perfect for everyday wear",
        brand: "Allen Solly",
        model: "Casual Shirt",
        rating: 4.3,
        reviews: 450,
        inStock: true,
        material: "100% Cotton",
        warranty: "Exchange within 30 days"
    },
    {
        id: 10,
        name: "Men's Slim Fit Jeans",
        category: "fashion",
        price: 1899,
        originalPrice: 2999,
        image: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=400",
        description: "Comfortable stretch denim jeans with modern slim fit",
        brand: "Levi's",
        model: "511 Slim Fit",
        rating: 4.5,
        reviews: 1250,
        inStock: true,
        material: "Denim - Cotton Blend",
        warranty: "Exchange within 30 days"
    },
    {
        id: 11,
        name: "Men's Formal Blazer",
        category: "fashion",
        price: 4999,
        originalPrice: 7999,
        image: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=400",
        description: "Elegant formal blazer for professional occasions",
        brand: "Raymond",
        model: "Formal Blazer",
        rating: 4.6,
        reviews: 320,
        inStock: true,
        material: "Polyester Blend",
        warranty: "Exchange within 30 days"
    },
    {
        id: 12,
        name: "Men's T-Shirt Pack",
        category: "fashion",
        price: 899,
        originalPrice: 1499,
        image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400",
        description: "Pack of 3 comfortable cotton t-shirts in assorted colors",
        brand: "H&M",
        model: "Basic T-Shirt",
        rating: 4.4,
        reviews: 2340,
        inStock: true,
        material: "100% Cotton",
        warranty: "Exchange within 30 days"
    },

    // ===== FASHION - WOMEN =====
    {
        id: 13,
        name: "Women's Ethnic Kurti",
        category: "fashion",
        price: 1299,
        originalPrice: 2199,
        image: "https://images.unsplash.com/photo-1583391733956-6c78276477e2?w=400",
        description: "Beautiful printed kurti with elegant design",
        brand: "Libas",
        model: "Printed Kurti",
        rating: 4.5,
        reviews: 890,
        inStock: true,
        material: "Rayon",
        warranty: "Exchange within 30 days"
    },
    {
        id: 14,
        name: "Women's Denim Jacket",
        category: "fashion",
        price: 2499,
        originalPrice: 3999,
        image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400",
        description: "Trendy denim jacket, perfect for casual outings",
        brand: "Zara",
        model: "Denim Jacket",
        rating: 4.6,
        reviews: 670,
        inStock: true,
        material: "Denim",
        warranty: "Exchange within 30 days"
    },
    {
        id: 15,
        name: "Women's Summer Dress",
        category: "fashion",
        price: 1799,
        originalPrice: 2999,
        image: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400",
        description: "Light and breezy summer dress with floral print",
        brand: "AND",
        model: "Floral Dress",
        rating: 4.4,
        reviews: 1120,
        inStock: true,
        material: "Cotton Blend",
        warranty: "Exchange within 30 days"
    },
    {
        id: 16,
        name: "Women's Formal Blazer",
        category: "fashion",
        price: 3999,
        originalPrice: 5999,
        image: "https://images.unsplash.com/photo-1591369822096-ffd140ec948f?w=400",
        description: "Professional blazer for office and formal events",
        brand: "Van Heusen",
        model: "Formal Blazer",
        rating: 4.5,
        reviews: 430,
        inStock: true,
        material: "Polyester",
        warranty: "Exchange within 30 days"
    },

    // ===== FOOTWEAR =====
    {
        id: 17,
        name: "Nike Air Max 270",
        category: "footwear",
        price: 12995,
        originalPrice: 16995,
        image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400",
        description: "Iconic Nike sneakers with Air Max cushioning",
        brand: "Nike",
        model: "Air Max 270",
        rating: 4.7,
        reviews: 2890,
        inStock: true,
        material: "Mesh & Synthetic",
        warranty: "6 Months Warranty"
    },
    {
        id: 18,
        name: "Adidas Ultraboost 23",
        category: "footwear",
        price: 15999,
        originalPrice: 18999,
        image: "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=400",
        description: "Premium running shoes with Boost technology",
        brand: "Adidas",
        model: "Ultraboost 23",
        rating: 4.8,
        reviews: 1670,
        inStock: true,
        material: "Primeknit",
        warranty: "6 Months Warranty"
    },
    {
        id: 19,
        name: "Puma RS-X",
        category: "footwear",
        price: 7999,
        originalPrice: 10999,
        image: "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400",
        description: "Retro-style chunky sneakers with bold design",
        brand: "Puma",
        model: "RS-X",
        rating: 4.5,
        reviews: 890,
        inStock: true,
        material: "Synthetic Leather",
        warranty: "6 Months Warranty"
    },
    {
        id: 20,
        name: "Formal Leather Shoes",
        category: "footwear",
        price: 3499,
        originalPrice: 5499,
        image: "https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=400",
        description: "Classic formal leather shoes for office and events",
        brand: "Red Tape",
        model: "Formal Lace-up",
        rating: 4.4,
        reviews: 560,
        inStock: true,
        material: "Genuine Leather",
        warranty: "3 Months Warranty"
    },
    {
        id: 21,
        name: "Women's Heels",
        category: "footwear",
        price: 2499,
        originalPrice: 3999,
        image: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400",
        description: "Elegant stiletto heels for parties and formal occasions",
        brand: "Metro",
        model: "Stiletto Heels",
        rating: 4.3,
        reviews: 720,
        inStock: true,
        material: "Synthetic",
        warranty: "3 Months Warranty"
    },
    {
        id: 22,
        name: "Casual Sandals",
        category: "footwear",
        price: 1299,
        originalPrice: 1999,
        image: "https://images.unsplash.com/photo-1603487742131-4160ec999306?w=400",
        description: "Comfortable casual sandals for everyday wear",
        brand: "Bata",
        model: "Casual Sandals",
        rating: 4.2,
        reviews: 1450,
        inStock: true,
        material: "Rubber",
        warranty: "3 Months Warranty"
    },

    // ===== HOME & FURNITURE =====
    {
        id: 23,
        name: "Ergonomic Office Chair",
        category: "home",
        price: 12999,
        originalPrice: 18999,
        image: "https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=400",
        description: "Comfortable ergonomic chair with lumbar support",
        brand: "Green Soul",
        model: "Ergonomic Chair",
        rating: 4.5,
        reviews: 890,
        inStock: true,
        material: "Mesh & Metal",
        warranty: "1 Year Warranty"
    },
    {
        id: 24,
        name: "Queen Size Bed",
        category: "home",
        price: 24999,
        originalPrice: 34999,
        image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=400",
        description: "Modern wooden bed with storage drawers",
        brand: "Urban Ladder",
        model: "Queen Bed with Storage",
        rating: 4.6,
        reviews: 450,
        inStock: true,
        material: "Engineered Wood",
        warranty: "1 Year Warranty"
    },
    {
        id: 25,
        name: "LED Table Lamp",
        category: "home",
        price: 1499,
        originalPrice: 2499,
        image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400",
        description: "Modern LED lamp with adjustable brightness",
        brand: "Philips",
        model: "LED Desk Lamp",
        rating: 4.4,
        reviews: 1230,
        inStock: true,
        material: "Plastic & Metal",
        warranty: "6 Months Warranty"
    },
    {
        id: 26,
        name: "Wall Clock",
        category: "home",
        price: 899,
        originalPrice: 1499,
        image: "https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?w=400",
        description: "Decorative wall clock with silent quartz movement",
        brand: "Ajanta",
        model: "Wall Clock",
        rating: 4.3,
        reviews: 2340,
        inStock: true,
        material: "Plastic",
        warranty: "1 Year Warranty"
    },
    {
        id: 27,
        name: "Sofa Set 3+2",
        category: "home",
        price: 45999,
        originalPrice: 65999,
        image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400",
        description: "Comfortable fabric sofa set for living room",
        brand: "Godrej Interio",
        model: "3+2 Sofa Set",
        rating: 4.7,
        reviews: 320,
        inStock: true,
        material: "Fabric & Wood",
        warranty: "2 Year Warranty"
    },
    {
        id: 28,
        name: "Dining Table Set",
        category: "home",
        price: 19999,
        originalPrice: 29999,
        image: "https://images.unsplash.com/photo-1617806118233-18e1de247200?w=400",
        description: "4-seater dining table with chairs",
        brand: "Nilkamal",
        model: "Dining Set",
        rating: 4.4,
        reviews: 560,
        inStock: true,
        material: "Wood & Glass",
        warranty: "1 Year Warranty"
    },

    // ===== BEAUTY & CARE =====
    {
        id: 29,
        name: "Lakme Makeup Kit",
        category: "beauty",
        price: 2499,
        originalPrice: 3999,
        image: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400",
        description: "Complete makeup kit with essential cosmetics",
        brand: "Lakme",
        model: "Bridal Makeup Kit",
        rating: 4.5,
        reviews: 1890,
        inStock: true,
        material: "Cosmetics",
        warranty: "No Warranty"
    },
    {
        id: 30,
        name: "L'Oreal Hair Serum",
        category: "beauty",
        price: 599,
        originalPrice: 899,
        image: "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=400",
        description: "Nourishing hair serum for smooth and shiny hair",
        brand: "L'Oreal Paris",
        model: "Hair Serum",
        rating: 4.6,
        reviews: 3450,
        inStock: true,
        material: "Hair Care",
        warranty: "No Warranty"
    },
    {
        id: 31,
        name: "Nivea Face Cream",
        category: "beauty",
        price: 299,
        originalPrice: 449,
        image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400",
        description: "Moisturizing face cream for daily use",
        brand: "Nivea",
        model: "Soft Cream",
        rating: 4.4,
        reviews: 5670,
        inStock: true,
        material: "Skin Care",
        warranty: "No Warranty"
    },
    {
        id: 32,
        name: "Perfume Set",
        category: "beauty",
        price: 1999,
        originalPrice: 2999,
        image: "https://images.unsplash.com/photo-1541643600914-78b084683601?w=400",
        description: "Luxury perfume set with long-lasting fragrance",
        brand: "Engage",
        model: "Perfume Combo",
        rating: 4.3,
        reviews: 2340,
        inStock: true,
        material: "Fragrance",
        warranty: "No Warranty"
    },

    // ===== SPORTS & FITNESS =====
    {
        id: 33,
        name: "Yoga Mat",
        category: "sports",
        price: 799,
        originalPrice: 1299,
        image: "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=400",
        description: "Non-slip yoga mat with extra cushioning",
        brand: "Strauss",
        model: "Yoga Mat",
        rating: 4.5,
        reviews: 1230,
        inStock: true,
        material: "PVC",
        warranty: "6 Months Warranty"
    },
    {
        id: 34,
        name: "Dumbbell Set",
        category: "sports",
        price: 2499,
        originalPrice: 3999,
        image: "https://images.unsplash.com/photo-1638536532686-d610adfc8e5c?w=400",
        description: "Adjustable dumbbell set for home gym",
        brand: "Kore",
        model: "Dumbbell 10kg Set",
        rating: 4.6,
        reviews: 890,
        inStock: true,
        material: "Iron",
        warranty: "1 Year Warranty"
    },
    {
        id: 35,
        name: "Cricket Bat",
        category: "sports",
        price: 3999,
        originalPrice: 5999,
        image: "https://images.unsplash.com/photo-1624526267942-ab0ff8a3e972?w=400",
        description: "Professional cricket bat made from Kashmir willow",
        brand: "MRF",
        model: "Genius Grand",
        rating: 4.7,
        reviews: 560,
        inStock: true,
        material: "Kashmir Willow",
        warranty: "3 Months Warranty"
    },
    {
        id: 36,
        name: "Football",
        category: "sports",
        price: 999,
        originalPrice: 1499,
        image: "https://images.unsplash.com/photo-1614632537197-38a17061c2bd?w=400",
        description: "Official size football for training and matches",
        brand: "Nivia",
        model: "Storm Football",
        rating: 4.4,
        reviews: 2340,
        inStock: true,
        material: "Rubber",
        warranty: "3 Months Warranty"
    },

    // ===== BOOKS & STATIONERY =====
    {
        id: 37,
        name: "Atomic Habits",
        category: "books",
        price: 399,
        originalPrice: 599,
        image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400",
        description: "Best-selling book on building good habits",
        brand: "Penguin",
        model: "Paperback",
        rating: 4.9,
        reviews: 15670,
        inStock: true,
        material: "Paper",
        warranty: "No Warranty"
    },
    {
        id: 38,
        name: "The Psychology of Money",
        category: "books",
        price: 349,
        originalPrice: 499,
        image: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=400",
        description: "Essential book about wealth and happiness",
        brand: "Jaico",
        model: "Paperback",
        rating: 4.8,
        reviews: 12340,
        inStock: true,
        material: "Paper",
        warranty: "No Warranty"
    },
    {
        id: 39,
        name: "Notebook Set",
        category: "books",
        price: 299,
        originalPrice: 499,
        image: "https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=400",
        description: "Pack of 5 quality notebooks for students",
        brand: "Classmate",
        model: "Single Line",
        rating: 4.5,
        reviews: 4560,
        inStock: true,
        material: "Paper",
        warranty: "No Warranty"
    },
    {
        id: 40,
        name: "Pen Set",
        category: "books",
        price: 199,
        originalPrice: 349,
        image: "https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=400",
        description: "Premium pen set with smooth writing experience",
        brand: "Parker",
        model: "Jotter Set",
        rating: 4.6,
        reviews: 3450,
        inStock: true,
        material: "Metal & Plastic",
        warranty: "6 Months Warranty"
    }
];

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = productsData;
}
